# Generated by Django 5.2.14 on 2026-06-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="estado_pago",
            field=models.CharField(
                choices=[("pendiente", "Pendiente"), ("pagada", "Pagada")],
                default="pendiente",
                max_length=15,
            ),
        ),
    ]
