# Generated by Django 5.2.14 on 2026-06-07 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0012_alter_cita_estado"),
        ("facturacion", "0002_factura_estado_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallefactura",
            name="servicio_cambiado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detalles_modificados",
                to="citas.servicio",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="fecha_cambio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="factura",
            name="motivo_cambio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="factura",
            name="servicio_cambiado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas_modificadas",
                to="citas.servicio",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="servicio_original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas_originales",
                to="citas.servicio",
            ),
        ),
    ]
