# Generated by Django 5.2.14 on 2026-06-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_detallefactura_servicio_cambiado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='servicio_cambiado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_cambio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='motivo_cambio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='servicio_cambiado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='servicio_original',
        ),
    ]
