# Generated by Django 5.2.14 on 2026-05-31 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('veterinario', 'Veterinario'), ('resepcionista', 'Resepcionista'), ('propietario', 'Propietario')], default='propietario', max_length=20),
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad')], max_length=20)),
                ('documento', models.CharField(max_length=10, unique=True)),
                ('foto', models.ImageField(blank=True, default='perfiles/default.svg', null=True, upload_to='perfiles/')),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_contratacion', models.DateTimeField(auto_now_add=True)),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('nocturno', 'Nocturno')], default='mañana', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcionista', to='usuarios.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
