# Generated by Django 5.2.14 on 2026-05-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0007_alter_usuario_rol_recepcionista"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("veterinario", "Veterinario"),
                    ("recepcionista", "Resepcionista"),
                    ("propietario", "Propietario"),
                ],
                default="propietario",
                max_length=20,
            ),
        ),
    ]
