# Generated by Django 5.2.14 on 2026-06-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0008_alter_usuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrador",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="propietario",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="recepcionista",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="veterinario",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
