# Generated by Django 6.0.5 on 2026-05-15 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaServicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_categoria", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("motivo_consulta", models.CharField(max_length=200)),
                (
                    "notas_adicionales",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                            ("finalizada", "Finalizada"),
                            ("en_proceso", "En Proceso"),
                        ],
                        default="confirmada",
                        max_length=15,
                    ),
                ),
                ("recordatorio_enviado", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("anamnesis", models.TextField()),
                ("examen_fisico", models.TextField()),
                ("diagnostico_presuntivo", models.TextField()),
                ("diagnostico_definitivo", models.TextField()),
                ("plan_terapeutico", models.TextField()),
                ("observaciones", models.TextField()),
                (
                    "peso_en_consulta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(35),
                            django.core.validators.MaxValueValidator(42),
                        ],
                    ),
                ),
                ("frecuencia_cardiaca", models.IntegerField()),
                ("frecuencia_respiratoria", models.IntegerField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoriaClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_consulta", models.DateField()),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(35),
                            django.core.validators.MaxValueValidator(42),
                        ],
                    ),
                ),
                ("frecuencia_cardiaca", models.IntegerField(blank=True, null=True)),
                ("frecuencia_respiratoria", models.IntegerField(blank=True, null=True)),
                ("motivo_consulta", models.CharField(max_length=200)),
                ("anamnesis", models.TextField()),
                ("examen_fisico", models.TextField()),
                ("diagnostico", models.TextField()),
                ("tratamiento", models.TextField()),
                ("medicamentos_dosis", models.TextField()),
                ("recomendaciones", models.TextField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "archivo_adjunto",
                    models.FileField(
                        blank=True, null=True, upload_to="historia_clinica/"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistorialServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_comercial", models.CharField(max_length=150)),
                ("principio_activo", models.CharField(max_length=150)),
                ("presentacion", models.CharField(max_length=80)),
                ("concentracion", models.CharField(max_length=80)),
                ("via_administracion", models.CharField(max_length=80)),
                ("horas_intervalo", models.IntegerField()),
                ("fabricante", models.CharField(max_length=150)),
                ("stock_actual", models.IntegerField()),
                ("stock_minimo", models.IntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fecha_vencimiento", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=200)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("duracion_minutos", models.IntegerField()),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tratamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("medicamento", models.CharField(max_length=200)),
                (
                    "dosis",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("frecuencia", models.CharField(max_length=80)),
                ("instrucciones", models.TextField()),
                ("duracion_dias", models.IntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("finalizado", "Finalizado"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("fabricante", models.CharField(max_length=50)),
                ("enfermedades", models.TextField()),
                ("dosis_total", models.IntegerField()),
                ("intervalo_dosis", models.IntegerField()),
                ("refuerzo_meses", models.IntegerField()),
                ("edad_minima_dias", models.IntegerField()),
                ("requiere_frio", models.BooleanField()),
                ("lote", models.CharField(blank=True, max_length=80, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField()),
                ("fecha_creacion", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Vacunacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_aplicacion", models.DateField(auto_now_add=True)),
                ("numero_dosis", models.IntegerField()),
                ("fecha_proxima", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
