# Generated by Django 5.2.14 on 2026-05-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='tipo_registro',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('vacunacion', 'Vacunación'), ('servicio', 'Servicio')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
