# Generated by Django 5.2.14 on 2026-05-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0003_historiaclinica_tipo_registro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historiaclinica",
            name="archivo_adjunto",
        ),
        migrations.RemoveField(
            model_name="historiaclinica",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="historiaclinica",
            name="fecha_creacion",
        ),
        migrations.AlterField(
            model_name="historiaclinica",
            name="anamnesis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historiaclinica",
            name="diagnostico",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historiaclinica",
            name="examen_fisico",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historiaclinica",
            name="medicamentos_dosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historiaclinica",
            name="motivo_consulta",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historiaclinica",
            name="temperatura",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historiaclinica",
            name="tratamiento",
            field=models.TextField(blank=True, null=True),
        ),
    ]
