# Generated by Django 5.2.14 on 2026-05-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_remove_historiaclinica_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada'), ('en_proceso', 'En Proceso'), ('no_asistio', 'No Asistio')], default='confirmada', max_length=15),
        ),
    ]
