# Generated by Django 5.2.14 on 2026-05-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_rename_fecha_proxima_vacunacion_proxima_dosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuna',
            name='activo',
        ),
        migrations.AddField(
            model_name='vacuna',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
    ]
