# Generated by Django 5.2.14 on 2026-06-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0011_remove_vacuna_fecha_vencimiento_cita_vacuna"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                    ("atendida", "Atendida"),
                    ("facturada", "Facturada"),
                    ("en_proceso", "En Proceso"),
                    ("no_asistio", "No Asistio"),
                ],
                default="pendiente",
                max_length=15,
            ),
        ),
    ]
