# Generated by Django 5.2.14 on 2026-06-14 00:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0012_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_cambio_servicio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio_realizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_realizadas', to='citas.servicio'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='frecuencia_cardiaca',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='frecuencia_respiratoria',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.DeleteModel(
            name='HistorialServicio',
        ),
    ]
