# Generated by Django 5.2.14 on 2026-06-07 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0012_alter_cita_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="motivo_cambio_servicio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cita",
            name="servicio_realizado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="citas_realizadas",
                to="citas.servicio",
            ),
        ),
    ]
