# Generated by Django 5.2.14 on 2026-06-09 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0013_cita_motivo_cambio_servicio_cita_servicio_realizado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="frecuencia_cardiaca",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(40),
                    django.core.validators.MaxValueValidator(300),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="frecuencia_respiratoria",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.DeleteModel(
            name="HistorialServicio",
        ),
    ]
