# Generated by Django 5.2.14 on 2026-06-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0013_cita_motivo_cambio_servicio_cita_servicio_realizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='motivo_cambio_servicio',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='servicio_realizado',
        ),
    ]
