# Generated by Django 5.2.14 on 2026-06-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0014_remove_cita_motivo_cambio_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
