# Generated by Django 5.2.14 on 2026-06-23 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0015_alter_consulta_hora_fin_alter_consulta_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='consulta',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
