# Generated by Django 5.2.14 on 2026-06-23 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0016_remove_consulta_hora_fin_remove_consulta_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
