# Generated by Django 5.2.14 on 2026-05-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(default='Desconocido', max_length=20),
            preserve_default=False,
        ),
    ]
