# flake8: noqa
from .dashboard import *
from .mascota import *
from .consultas import *
from .historiaclinica import *
from .categoriaservicio import *
from .servicio import *
from .factura import *
from .detalle_factura import *
from .especie import *
from .raza import *
from .vacuna import *
from .vacunacion import *
from .plantilla_notificacion import *
from .notificacion import *
from .especialidad import *
from .veterinario import *
from .propietario import *
from .cita import *
from .recepcionista import *
